"""Generate the typed ``postgkyl.clap`` module from the pgkyl click commands.

The pgkyl command line is the single source of truth: every command and option
already carries a name, type, default and help string. This module introspects
that metadata and emits a real ``clap.py`` with one typed method per command, so
that editors/Pylance get full signature and docstring help with no runtime
tricks (a purely dynamic wrapper would not be statically visible).

Usage:
    python -m postgkyl.clap._clap_gen          # rewrite src/postgkyl/clap/clap.py
    python -m postgkyl.clap._clap_gen --check   # exit non-zero if clap.py is stale

The ``test_clap_in_sync`` test (or a build step) can call :func:`render` to keep
the committed ``clap.py`` from drifting away from the commands.
"""

from __future__ import annotations

import inspect
import keyword
import os
import sys

import click

from postgkyl.pgkyl import cli

# ``load`` is provided by hand on _Session (it needs to stash the file names),
# so it is not generated here.
_SKIP = {"load"}

_HEADER = '''"""Typed, scriptable pgkyl clap.

GENERATED by ``postgkyl.clap._clap_gen`` from the pgkyl click commands. Do not edit
by hand; run ``python -m postgkyl.clap._clap_gen`` to regenerate after changing
commands.

    from postgkyl.clap import PgkylSession
    pg = PgkylSession()
    pg.load("file.gkyl")
    pg.gk_rz()
    pg.plot()
"""

from typing import Literal

from postgkyl.pgkyl import cli
from postgkyl.clap.scripting import _Session


def _cmd(name: str):
  return cli.commands[name]


def _flag(value, flag_value):
  """Translate an clap boolean for a click optional-value flag.

  ``True`` enables the flag with its default behaviour (click's ``flag_value``),
  ``False`` disables it (``None``); a string passes straight through as an
  explicit override. This lets the friendly ``bool`` clap default map onto what
  the command already expects without the commands needing to know about it.
  """
  if value is True:
    return flag_value
  if value is False:
    return None
  return value


class PgkylSession(_Session):
'''


def _is_optional_value_flag(param: click.Parameter) -> bool:
  """Click "optional value" flag: a flag whose ``flag_value`` is not boolean.

  These accept ``--opt`` (use ``flag_value``) or ``--opt FILE`` (override), and
  default to ``None`` when absent. They wrap into the clap as ``bool | str``.
  """
  return (
      getattr(param, "is_flag", False)
      and not isinstance(getattr(param, "flag_value", None), bool))


def _annotation(param: click.Parameter) -> str:
  """Map a click parameter type to a Python type annotation string."""
  ctype = param.type
  name = getattr(ctype, "name", "text")
  if _is_optional_value_flag(param):
    base = "bool | str"
  elif getattr(param, "is_flag", False) or name == "boolean":
    base = "bool"
  elif name == "integer":
    base = "int"
  elif name in ("float", "floatrange"):
    base = "float"
  elif name == "choice":
    base = "Literal[" + ", ".join(repr(c) for c in ctype.choices) + "]"
  else:
    base = "str"
  # Variadic arguments / multiple options collect into a tuple.
  if getattr(param, "multiple", False) or getattr(param, "nargs", 1) == -1:
    return f"tuple[{base}, ...]"
  return base


def _is_collection(param: click.Parameter) -> bool:
  return getattr(param, "multiple", False) or getattr(param, "nargs", 1) == -1


def _default_repr(param: click.Parameter) -> str:
  """Python source for a parameter default; ``None`` when click leaves it unset."""
  default = param.default
  # click >=8.2 uses a Sentinel for "no default was given".
  if default is None or repr(default).startswith("Sentinel"):
    is_bool_flag = getattr(param, "is_flag", False) and not _is_optional_value_flag(param)
    return "False" if is_bool_flag else "None"
  if _is_collection(param):
    return "()"
  return repr(default)


def _safe_name(name: str) -> str:
  return name + "_" if keyword.iskeyword(name) else name


def _signature_parts(command: click.Command):
  """Return (required_params, optional_params) split for a valid Python signature."""
  required, optional = [], []
  for param in command.params:
    if param.name == "help":
      continue
    # Required positional arguments (no default) must come first.
    if isinstance(param, click.Argument) and param.required and not _is_collection(param):
      required.append(param)
    else:
      optional.append(param)
  return required, optional


def _render_command(cli_name: str, command: click.Command) -> str:
  method = cli_name.replace("-", "_")
  required, optional = _signature_parts(command)

  params_src = []
  for param in required:
    params_src.append(f"{_safe_name(param.name)}: {_annotation(param)}")
  for param in optional:
    ann = _annotation(param)
    default = _default_repr(param)
    if default == "None" and not ann.startswith("tuple"):
      ann = f"{ann} | None"
    params_src.append(f"{_safe_name(param.name)}: {ann} = {default}")

  joined = ",\n      ".join(params_src)
  signature = f"  def {method}(self,\n      {joined}):" if params_src else f"  def {method}(self):"

  # Docstring: command help + per-parameter help. Run the help through
  # ``inspect.cleandoc`` so the embedded text is independent of how the
  # installed click version preserves docstring indentation; otherwise the
  # rendered output (and the ``test_clap_in_sync`` check) would differ between
  # environments purely on leading whitespace.
  doc = "\n".join(
      line.rstrip() for line in inspect.cleandoc(command.help or "").splitlines())
  lines = ['    """' + (doc if doc else method)]
  all_params = required + optional
  if all_params:
    lines.append("")
    lines.append("    Args:")
    for param in all_params:
      opts = ", ".join(param.opts) if param.opts else param.name
      phelp = (getattr(param, "help", None) or "").strip().replace("\n", " ")
      lines.append(f"      {param.name}: ({opts}) {phelp}".rstrip())
  lines.append('    """')
  docstring = "\n".join(lines)

  def _pass_value(param: click.Parameter) -> str:
    name = _safe_name(param.name)
    if _is_optional_value_flag(param):
      return f"_flag({name}, {param.flag_value!r})"
    return name

  passes = ", ".join(
      f"{param.name}={_pass_value(param)}" for param in all_params)
  call = f'    return self._run(_cmd("{cli_name}"){", " + passes if passes else ""})'

  return f"{signature}\n{docstring}\n{call}\n"


def render() -> str:
  """Return the full source text of the generated ``clap.py``."""
  blocks = []
  for cli_name in sorted(cli.commands):
    if cli_name in _SKIP:
      continue
    blocks.append(_render_command(cli_name, cli.commands[cli_name]))
  return _HEADER + "\n".join(blocks)


def _target_path() -> str:
  return os.path.join(os.path.dirname(__file__), "clap.py")


def main(argv=None) -> int:
  argv = argv if argv is not None else sys.argv[1:]
  text = render()
  path = _target_path()
  if "--check" in argv:
    try:
      with open(path, "r") as fh:
        current = fh.read()
    except FileNotFoundError:
      current = None
    if current != text:
      print("postgkyl/clap/clap.py is stale; run 'python -m postgkyl.clap._clap_gen'.")
      return 1
    print("postgkyl/clap/clap.py is up to date.")
    return 0
  with open(path, "w") as fh:
    fh.write(text)
  print(f"Wrote {path}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
