"""Typed, scriptable pgkyl clap.

GENERATED by ``postgkyl.clap._clap_gen`` from the pgkyl click commands. Do not edit
by hand; run ``python -m postgkyl.clap._clap_gen`` to regenerate after changing
commands.

    from postgkyl.clap import PgkylSession
    pg = PgkylSession()
    pg.load("file.gkyl")
    pg.gk_rz()
    pg.plot()
"""

from typing import Literal

from postgkyl.pgkyl import cli
from postgkyl.clap.scripting import _Session


def _cmd(name: str):
  return cli.commands[name]


def _flag(value, flag_value):
  """Translate an clap boolean for a click optional-value flag.

  ``True`` enables the flag with its default behaviour (click's ``flag_value``),
  ``False`` disables it (``None``); a string passes straight through as an
  explicit override. This lets the friendly ``bool`` clap default map onto what
  the command already expects without the commands needing to know about it.
  """
  if value is True:
    return flag_value
  if value is False:
    return None
  return value


class PgkylSession(_Session):
  def activate(self,
      tag: str | None = None,
      index: str | None = None,
      focused: bool = False):
    """Select datasets(s) to pass further down the command chain.

Datasets are indexed starting 0. Multiple datasets can be selected using a comma
separated list or a range specifier. Unless '--focused' is selected, all unselected
datasets will be deactivated.

'--tag' and '--index' allow to specify tags and indices. The not specified, 'activate'
applies to all. Both parameters support comma-separated values. '--index' also
supports slices following the Python conventions, e.g., '3:7' or ':-5:2'.

'info' command (especially with the '-ac' flags) can be helpful when
activating/deactivating multiple datasets.

    Args:
      tag: (--tag, -t) Tag(s) to apply to (comma-separated).
      index: (--index, -i) Dataset indices (e.g., '1', '0,2,5', or '1:6:2').
      focused: (--focused, -f) Leave unspecified datasets untouched.
    """
    return self._run(_cmd("activate"), tag=tag, index=index, focused=focused)

  def agyro(self,
      measure: Literal['swisdak', 'frobenius'] = 'frobenius',
      pressure: str = 'pressure',
      bfield: str = 'field',
      tag: str | None = None,
      label: str | None = None):
    """Compute a measure of agyrotropy.

Default measure is taken from Swisdak 2015. Optionally computes agyrotropy as
Frobenius norm of agyrotropic pressure tensor.

    Args:
      measure: (--measure, -m) Specify how to calculate agyrotropy.
      pressure: (--pressure, -p) Tag for input pressure.
      bfield: (--bfield, -b) Tag for input EM field.
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("agyro"), measure=measure, pressure=pressure, bfield=bfield, tag=tag, label=label)

  def animate(self,
      use: str | None = None,
      grouptags: bool = False,
      squeeze: bool = False,
      subplots: bool = False,
      nSubplotRow: int | None = None,
      nSubplotCol: int | None = None,
      transpose: bool = False,
      contour: bool = False,
      clevels: str | None = None,
      quiver: bool = False,
      streamline: bool = False,
      sdensity: float | None = None,
      arrowstyle: str | None = None,
      group: Literal['0', '1'] | None = None,
      scatter: bool = False,
      markersize: float | None = None,
      linewidth: float | None = None,
      linestyle: Literal['solid', 'dashed', 'dotted', 'dashdot'] | None = None,
      color: str | None = None,
      style: str | None = None,
      diverging: bool = False,
      arg: str | None = None,
      fixaspect: bool = False,
      logx: bool = False,
      logy: bool = False,
      logz: bool = False,
      xshift: float = 0.0,
      yshift: float = 0.0,
      zshift: float = 0.0,
      xscale: float = 1.0,
      yscale: float = 1.0,
      zscale: float = 1.0,
      float: bool = False,
      xmax: float | None = None,
      xmin: float | None = None,
      ymax: float | None = None,
      ymin: float | None = None,
      zmax: float | None = None,
      zmin: float | None = None,
      xlim: str | None = None,
      ylim: str | None = None,
      zlim: str | None = None,
      cutoffglobalrange: float | None = None,
      legend: bool = True,
      colorbar: bool = True,
      forcelegend: bool = False,
      xlabel: str | None = None,
      ylabel: str | None = None,
      clabel: str | None = None,
      title: str | None = None,
      notitle: bool = False,
      interval: int = 100,
      save: bool = False,
      saveas: str | None = None,
      fps: int | None = None,
      dpi: int | None = None,
      edgecolors: str | None = None,
      showgrid: bool = True,
      collected: bool = False,
      hashtag: bool = False,
      show: bool = True,
      saveframes: str | None = None,
      nproc: int = 1,
      tmpdir: str | None = None,
      figsize: str | None = None,
      multiblock: bool = False):
    """Animate the actively loaded dataset and show resulting plots in a loop.

Typically, the datasets are loaded using wildcard/regex feature of the -f option to
the main pgkyl executable.

    Args:
      use: (--use, -u) Specify a tag to plot.
      grouptags: (--grouptags) Group coresponding tagged frames.
      squeeze: (--squeeze, -p) Squeeze the components into one panel.
      subplots: (--subplots, -b) Make subplots from multiple datasets.
      nSubplotRow: (--nsubplotrow) Manually set the number of rows for subplots.
      nSubplotCol: (--nsubplotcol) Manually set the number of columns for subplots.
      transpose: (--transpose) Transpose axes.
      contour: (--contour, -c) Make contour plot.
      clevels: (--clevels) Specify levels for contours: either integer or start:end:nlevels
      quiver: (--quiver, -q) Make quiver plot.
      streamline: (--streamline, -l) Make streamline plot.
      sdensity: (--sdensity) Control density of the streamlines.
      arrowstyle: (--arrowstyle) Set the style for streamline arrows.
      group: (--group, -g) Switch to group mode.
      scatter: (--scatter, -s) Make scatter plot.
      markersize: (--markersize) Set marker size for scatter plots.
      linewidth: (--linewidth) Set the linewidth.
      linestyle: (--linestyle) Set the linestyle.
      color: (--color) Set color when available.
      style: (--style) Specify Matplotlib style file (default: Postgkyl).
      diverging: (--diverging, -d) Switch to diverging colormesh mode.
      arg: (--arg) Additional plotting arguments, e.g., '*--'.
      fixaspect: (--fix-aspect, -a) Enforce the same scaling on both axes.
      logx: (--logx) Set x-axis to log scale.
      logy: (--logy) Set y-axis to log scale.
      logz: (--logz) Set values of 2D plot to log scale.
      xshift: (--xshift) Value to shift the x-axis.
      yshift: (--yshift) Value to shift the y-axis.
      zshift: (--zshift) Value to shift the z-axis.
      xscale: (--xscale) Value to scale the x-axis.
      yscale: (--yscale) Value to scale the y-axis.
      zscale: (--zscale) Value to scale the z-axis.
      float: (--float) Choose min/max levels based on current frame (i.e., each frame uses a different color range).
      xmax: (--xmax) Set maximal x-value.
      xmin: (--xmin) Set minimal x-values.
      ymax: (--ymax) Set maximal y-value.
      ymin: (--ymin) Set minimal y-values.
      zmax: (--zmax) Set maximal z-value.
      zmin: (--zmin) Set minimal z-values.
      xlim: (--xlim) Set limits for the x-coordinate (lower,upper).
      ylim: (--ylim) Set limits for the y-coordinate (lower,upper).
      zlim: (--zlim) Set limits for the z-coordinate (lower,upper).
      cutoffglobalrange: (--cutoffglobalrange, -cogr) Specify middle percentile of data extrema to set y/z limits to
      legend: (--legend) Show legend.
      colorbar: (--colorbar) Show colorbar (2D animations), no colorbar improves animation performance
      forcelegend: (--force-legend) Force legend even when plotting a single dataset.
      xlabel: (-x, --xlabel) Specify a x-axis label.
      ylabel: (-y, --ylabel) Specify a y-axis label.
      clabel: (--clabel) Specify a label for colorbar.
      title: (--title) Specify a title.
      notitle: (--notitle) Do not show title.
      interval: (-i, --interval) Specify the animation interval.
      save: (--save) Save figure as PNG.
      saveas: (--saveas) Name to save the plot as.
      fps: (--fps) Specify frames per second for saving.
      dpi: (--dpi) DPI (resolution) for output.
      edgecolors: (--edgecolors, -e) Set color for cell edges.
      showgrid: (--showgrid) Show grid-lines.
      collected: (--collected) Animate a dataset that has been collected, i.e. a single dataset with time taken to be the first index.
      hashtag: (--hashtag) Turns on the pgkyl hashtag!
      show: (--show) Turn showing of the plot ON and OFF.
      saveframes: (--saveframes) Save individual frames as PNGs.
      nproc: (--nproc) Number of parallel processes for frame generation.
      tmpdir: (--tmpdir) Directory to place the temporary directory for parallel frame generation.
      figsize: (--figsize) Comma-separated values for x and y size.
      multiblock: (-m, --multiblock) Plots blocks from each frame together
    """
    return self._run(_cmd("animate"), use=use, grouptags=grouptags, squeeze=squeeze, subplots=subplots, nSubplotRow=nSubplotRow, nSubplotCol=nSubplotCol, transpose=transpose, contour=contour, clevels=clevels, quiver=quiver, streamline=streamline, sdensity=sdensity, arrowstyle=arrowstyle, group=group, scatter=scatter, markersize=markersize, linewidth=linewidth, linestyle=linestyle, color=color, style=style, diverging=diverging, arg=arg, fixaspect=fixaspect, logx=logx, logy=logy, logz=logz, xshift=xshift, yshift=yshift, zshift=zshift, xscale=xscale, yscale=yscale, zscale=zscale, float=float, xmax=xmax, xmin=xmin, ymax=ymax, ymin=ymin, zmax=zmax, zmin=zmin, xlim=xlim, ylim=ylim, zlim=zlim, cutoffglobalrange=cutoffglobalrange, legend=legend, colorbar=colorbar, forcelegend=forcelegend, xlabel=xlabel, ylabel=ylabel, clabel=clabel, title=title, notitle=notitle, interval=interval, save=save, saveas=saveas, fps=fps, dpi=dpi, edgecolors=edgecolors, showgrid=showgrid, collected=collected, hashtag=hashtag, show=show, saveframes=saveframes, nproc=nproc, tmpdir=tmpdir, figsize=figsize, multiblock=multiblock)

  def collect(self,
      sumdata: bool = False,
      period: float | None = None,
      offset: float = 0.0,
      chunk: int | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Collect data from the active datasets and create a new combined dataset.

The time-stamp in each of the active datasets is collected and used as the new X-axis.
Data can be collected in chunks, in which case several datasets are created, each with
the chunk-sized pieces collected into each new dataset.

    Args:
      sumdata: (-s, --sumdata) Sum data in the collected datasets (retain components).
      period: (-p, --period) Specify a period to create epoch data instead of time data.
      offset: (--offset) Specify an offset to create epoch data instead of time data.
      chunk: (-c, --chunk) Collect into chunks with specified length rather than into a single dataset.
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Specify a 'tag' for the result.
      label: (--label, -l) Specify the custom label for the result.
    """
    return self._run(_cmd("collect"), sumdata=sumdata, period=period, offset=offset, chunk=chunk, use=use, tag=tag, label=label)

  def config(self,
      gkylsoft: str | None = None,
      config_file: str | None = None):
    """Write postgkyl configuration (gkylsoft path) to the config file.

    Args:
      gkylsoft: (--gkylsoft, -g) Path to the gkylsoft directory. Uses GKYLSOFT_DIR env variable if not provided.
      config_file: (--config-file, -c) Config file to write. Default: ~/.postgkyl/gkylsoft_path, or the POSTGKYL_CONFIG env variable if set.
    """
    return self._run(_cmd("config"), gkylsoft=gkylsoft, config_file=config_file)

  def current(self,
      qbym: bool = False,
      use: str | None = None,
      tag: str = 'current',
      label: str = 'J'):
    """Accumulate current, sum over species of charge multiplied by flow.

    Args:
      qbym: (--qbym, -q) Flag for multiplying by charge/mass ratio instead of just charge.
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Tag for the resulting current array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("current"), qbym=qbym, use=use, tag=tag, label=label)

  def deactivate(self,
      tag: str | None = None,
      index: str | None = None,
      focused: bool = False):
    """Select datasets(s) to pass further down the command chain.

Datasets are indexed starting 0. Multiple datasets can be selected using a comma
separated list or a range specifier. Unless '--focused' is selected, all unselected
datasets will be activated.

'--tag' and '--index' allow to specify tags and indices. The not specified,
'deactivate' applies to all. Both parameters support comma-separated values. '--index'
also supports slices following the Python conventions, e.g., '3:7' or ':-5:2'.

'info' command (especially with the '-ac' flags) can be helpful when
activating/deactivating multiple datasets.

    Args:
      tag: (--tag, -t) Tag(s) to apply to (comma-separated).
      index: (--index, -i) Dataset indices (e.g., '1', '0,2,5', or '1:6:2').
      focused: (--focused, -f) Leave unspecified datasets untouched.
    """
    return self._run(_cmd("deactivate"), tag=tag, index=index, focused=focused)

  def dg_avg(self,
      z0: bool = False,
      z1: bool = False,
      z2: bool = False,
      z3: bool = False,
      z4: bool = False,
      z5: bool = False,
      comp: str | None = None,
      weight: str | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Average a DG field over specified directions.

Directions to average over are specified using the flags --z0, --z1, ... --z5.
The output has a reduced dimensionality corresponding to the averaged directions.

The geometric Jacobian <prefix>-geo_int_jacobgeo.gkyl (found next to the dataset)
is used as the weight if present, giving the weighted average int(f J dx) / int(J dx).
Override the weight file with --weight, or disable weighting with '--weight none'.

    Args:
      z0: (--z0) Average over direction 0.
      z1: (--z1) Average over direction 1.
      z2: (--z2) Average over direction 2.
      z3: (--z3) Average over direction 3.
      z4: (--z4) Average over direction 4.
      z5: (--z5) Average over direction 5.
      comp: (--comp, -c) Component index to select from the result (int or slice).
      weight: (--weight, -w) Weight file for the average. Defaults to <prefix>-geo_int_jacobgeo.gkyl found next to the dataset; pass a path to override, or 'none' to disable.
      use: (--use, -u) Tag to apply to. [default: all active]
      tag: (--tag, -t) Tag for the output dataset.
      label: (--label, -l) Label for the output dataset.
    """
    return self._run(_cmd("dg-avg"), z0=z0, z1=z1, z2=z2, z3=z3, z4=z4, z5=z5, comp=comp, weight=weight, use=use, tag=tag, label=label)

  def dg_evproj(self,
      z0: float | None = None,
      z1: float | None = None,
      z2: float | None = None,
      z3: float | None = None,
      z4: float | None = None,
      z5: float | None = None,
      comp: str | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Evaluate a DG field at specified coordinates and project onto a lower-dimensional basis.

Coordinates specified with --z0, --z1, ... --z5.

    Args:
      z0: (--z0) Physical coord to evaluate in direction 0.
      z1: (--z1) Physical coord to evaluate in direction 1.
      z2: (--z2) Physical coord to evaluate in direction 2.
      z3: (--z3) Physical coord to evaluate in direction 3.
      z4: (--z4) Physical coord to evaluate in direction 4.
      z5: (--z5) Physical coord to evaluate in direction 5.
      comp: (--comp, -c) Component index to select from the result (int or slice).
      use: (--use, -u) Tag to apply to. [default: all active]
      tag: (--tag, -t) Tag for the output dataset.
      label: (--label, -l) Label for the output dataset.
    """
    return self._run(_cmd("dg-evproj"), z0=z0, z1=z1, z2=z2, z3=z3, z4=z4, z5=z5, comp=comp, use=use, tag=tag, label=label)

  def dg_local_poly(self,
      use: str | None = None,
      npoints: int = 2):
    """Generate a discontinuous DG polynomial cellwise representation of the data.
The modal DG decomposition is evaluated with npoints per cell from one face
to the other. A NaN is inserted at every cell interface so that, when plotted,
the curve is broken at each interface and the inter-cell discontinuities of the DG solution
are visible.
Example (1D plot of the M0 moment along x at frame 0):
  pgkyl sim_3x2v_p1-ion_M0_0.gkyl dg-local-poly sel --z1=0.0 --z2=0.0 pl

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      npoints: (--npoints, -n) Number of evaluation points per cell.
    """
    return self._run(_cmd("dg-local-poly"), use=use, npoints=npoints)

  def differentiate(self,
      basis_type: Literal['ms', 'ns', 'mo'] | None = None,
      poly_order: int | None = None,
      interp: int | None = None,
      direction: int | None = None,
      read: bool | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Interpolate a derivative of DG data on a uniform mesh.

    Args:
      basis_type: (--basis_type, -b) Specify DG basis.
      poly_order: (--poly_order, -p) Specify polynomial order.
      interp: (--interp, -i) Interpolation onto a general mesh of specified amount
      direction: (--direction, -d) Direction of the derivative. [default: calculate all]
      read: (--read, -r) Read from general interpolation file.
      use: (--use, -u) Specify a 'tag' to apply to. [default: all]
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("differentiate"), basis_type=basis_type, poly_order=poly_order, interp=interp, direction=direction, read=read, use=use, tag=tag, label=label)

  def energetics(self,
      elc: str = 'elc',
      ion: str = 'ion',
      field: str = 'field',
      tag: str = 'energetics',
      label: str = 'E'):
    """Decomposes the components of the energy (kinetic, thermal, electromagnetic) for a two-species (electron, ion) plasma.

    Args:
      elc: (--elc, -e) Tag for electrons.
      ion: (--ion, -i) Tag for ions.
      field: (--field, -f) Tag for EM fields.
      tag: (--tag, -t) Tag for the result.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("energetics"), elc=elc, ion=ion, field=field, tag=tag, label=label)

  def euler(self,
      use: str | None = None,
      gas_gamma: float = 1.6666666666666667,
      variable_name: Literal['density', 'xvel', 'yvel', 'zvel', 'vel', 'pressure', 'ke', 'temp', 'sound', 'mach'] | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Compute Euler (five-moment) primitive and some derived variables
from fluid conserved variables.

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      gas_gamma: (-g, --gas_gamma) Gas adiabatic constant.
      variable_name: (-v, --variable_name) Variable to extract.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("euler"), use=use, gas_gamma=gas_gamma, variable_name=variable_name, tag=tag, label=label)

  def ev(self,
      chain: str,
      tag: str | None = None,
      label: str | None = None,
      all: bool = False):
    """Manipulate datasets using math expressions. Expressions are specified using Reverse Polish Notation (RPN).
Supported operators are:  '+', '-', '*', '/', 'dot', 'sqrt', 'sin', 'cos', 'tan', 'abs', 'avg', 'log', 'log10', 'max', 'min', 'max2', 'min2', 'mean', 'len', 'pow', 'sq', 'exp', 'grad', 'grad2', 'int', 'div', 'curl', 'scale_comp', 'scale_zi_axis'

    Args:
      chain: (chain)
      tag: (--tag, -t) Tag for the result
      label: (--label, -l) Custom label for the result
      all: (--all, -a) Ignore the status of a dataset
    """
    return self._run(_cmd("ev"), chain=chain, tag=tag, label=label, all=all)

  def extractinput(self,
      use: str | None = None):
    """Extract embedded input file from compatible BP files

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
    """
    return self._run(_cmd("extractinput"), use=use)

  def fft(self,
      psd: bool = False,
      iso: bool = False,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Calculate the Fourier Transform or the power-spectral density of input data.

Only works on 1D data at present.

    Args:
      psd: (-p, --psd) Limits output to positive frequencies and returns the power spectral density |FT|^2.
      iso: (-i, --iso) Bins power spectral density |FT|^2, making 1D power spectra from multi-dimensional data.
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("fft"), psd=psd, iso=iso, use=use, tag=tag, label=label)

  def gk_distf(self,
      name: str | None = None,
      species: str | None = None,
      suffix: str = '',
      jf_file: str | None = None,
      jacobvel_file: str | None = None,
      jacobtot_inv_file: str | None = None,
      frame: str | None = None,
      interp: int | None = None,
      c2p_vel: bool | str | None = None,
      mc2nu: bool | str | None = None,
      mapc2p: bool | str | None = None,
      block: int | None = None,
      tag: str = 'f'):
    """Gyrokinetics: load the distribution function from files containing the
distribution (f) times one or multiple Jacobians (J). The Jacobians are
divided out in order to output f. The distribution is interpolated, and
the interpolation can optionally use mappings to convert from computational
to physical coordinates.


Command line example:
  pgkyl gk-distf -n gk_lorentzian_mirror -s ion -f 0


Script example:
  import postgkyl as pg
  from postgkyl.commands import load_gk_distf

  distf = pg.commands.load_gk_distf(name="gk_lorentzian_mirror", species="ion", frame=0)

    Args:
      name: (--name, -n) Simulation name prefix (e.g. gk_lorentzian_mirror).
      species: (--species, -s) Species name (e.g. ion or elc).
      suffix: (--suffix) Use <name>-<species>_<suffix>_<frame>.gkyl as the input distribution.
      jf_file: (--Jf-file) Jf filename override. If omitted, the default naming convention is used.
      jacobvel_file: (--jacobvel-file) jacobvel filename override. If omitted, the default naming convention is used.
      jacobtot_inv_file: (--jacobtot-inv-file) jacobtot_inv filename override. If omitted, the default naming convention is used.
      frame: (--frame, -f) Frame number, comma separated values, or range. Use ':' for all frames and 'start:stop[:step]' for ranges.
      interp: (--interp, -i) Interpolation onto a general mesh of specified amount. User -i 0 for no interpolation.
      c2p_vel: (--c2p-vel, -v) Convert velocity-space computational to physical coordinates, using mapping in (optionally) given file (default *_mapc2p_vel.gkyl).
      mc2nu: (--mc2nu, -m) Convert non-uniform computational to field-aligned coordinates using mapping  in (optionally) given file (default: *-geo_corn_mc2nu_pos_deflated.gkyl).
      mapc2p: (--mapc2p, -p) Convert position-space computational to Cartesian (GKYL_GEOMETRY_MAPC2P) or  cylindrical (GKYL_GEOMETRY_TOKAMAK, GKYL_GEOMETRY_MIRROR) coordinates, using  mapping in (optionally) given file (default: *-geo_corn_mapc2p.gkyl)
      block: (--block, -b) Use block-specific files with _b<idx> prefix, e.g. -b 1 loads <name>_b1-*.gkyl.
      tag: (--tag, -t) Tag for output dataset.
    """
    return self._run(_cmd("gk-distf"), name=name, species=species, suffix=suffix, jf_file=jf_file, jacobvel_file=jacobvel_file, jacobtot_inv_file=jacobtot_inv_file, frame=frame, interp=interp, c2p_vel=_flag(c2p_vel, ''), mc2nu=_flag(mc2nu, ''), mapc2p=_flag(mapc2p, ''), block=block, tag=tag)

  def gk_energy_balance(self,
      name: str | None = None,
      species: str | None = None,
      path: str = './',
      relative_error: bool = False,
      multib: str = '-10',
      field_dot_file: tuple[str, ...] = None,
      apar_dot_file: tuple[str, ...] = None,
      fdot_file: tuple[str, ...] = None,
      source_file: tuple[str, ...] = None,
      bflux_xlower_file: tuple[str, ...] = None,
      bflux_ylower_file: tuple[str, ...] = None,
      bflux_zlower_file: tuple[str, ...] = None,
      bflux_xupper_file: tuple[str, ...] = None,
      bflux_yupper_file: tuple[str, ...] = None,
      bflux_zupper_file: tuple[str, ...] = None,
      f_file: tuple[str, ...] = None,
      field_file: tuple[str, ...] = None,
      apar_file: tuple[str, ...] = None,
      dt_file: str | None = None,
      logy: bool = False,
      absy: bool = False,
      xlabel: str = 'Time (s)',
      ylabel: str | None = None,
      title: str | None = None,
      indent_left: float = 0.0,
      add_width: float = 0.0,
      saveas: str | None = None):
    """
Gyrokinetics: Plot the energy balance of a simulation.
Requires the following files:
  <simulation_name>-field_energy_dot.gkyl
  ..._fdot_integrated_moms.gkyl
  ..._source_integrated_moms.gkyl
  ..._bflux_<direction><side>_integrated_HamiltonianMoments.gkyl
where ... means <simulation_name>-<species_name>, and we need these
files for each species. The last two files above are only needed if
the simulation had sources or non-periodic boundaries.
For electromagnetic simulations, the following file is also used
(if present):
  <simulation_name>-apar_energy_dot.gkyl
If the relative error is requested, these are also needed:
  ..._integrated_moms.gkyl
  <simulation_name>-field_energy.gkyl
  <simulation_name>-apar_energy.gkyl  (electromagnetic only)
  <simulation_name>-dt.gkyl


The default assumes these are in the current directory.
Alternatively, the full path to each file can be specified.
If passing the full path for the species-specific filed (e.g. --fdot_file)
pass * for the species name.


If simulation is multiblock, and you wish to specify files manually:
  1) Pass * for the block index.
  2) Use --multib/-m to specify desired blocks (or ommit to use all).

NOTE: this command cannot be combined with other postgkyl commands.

    Args:
      name: (--name, -n) Simulation name (also the file prefix, e.g. gk_sheath_1x2v_p1).
      species: (--species, -s) Comma-separated list of species names.
      path: (--path, -p) Path to simulation data.
      relative_error: (--relative_error, -r) Plot the relative error only.
      multib: (--multib, -m) Multiblock. Optional: pass block indices as comma-separated list or slice (start:stop:step). If no indices are given, all blocks are used.
      field_dot_file: (--field_dot_file) Integrated field energy rate of change.
      apar_dot_file: (--apar_dot_file) Integrated apar energy rate of change.
      fdot_file: (--fdot_file) Integrated moments of change in f over a time step.
      source_file: (--source_file) Integrated moments of the source(s).
      bflux_xlower_file: (--bflux_xlower_file) Integrated moments of boundary flux through lower x boundary.
      bflux_ylower_file: (--bflux_ylower_file) Integrated moments of boundary flux through lower y boundary.
      bflux_zlower_file: (--bflux_zlower_file) Integrated moments of boundary flux through lower z boundary.
      bflux_xupper_file: (--bflux_xupper_file) Integrated moments of boundary flux through upper x boundary.
      bflux_yupper_file: (--bflux_yupper_file) Integrated moments of boundary flux through upper y boundary.
      bflux_zupper_file: (--bflux_zupper_file) Integrated moments of boundary flux through upper z boundary.
      f_file: (--f_file) Integrated moments of f.
      field_file: (--field_file) Integrated field energy.
      apar_file: (--apar_file) Integrated apar energy.
      dt_file: (--dt_file) Time step.
      logy: (--logy) Logarithmic scale for y axis.
      absy: (--absy) Take absolute value of time traces.
      xlabel: (--xlabel) Label for the x axis.
      ylabel: (--ylabel) Label for the y axis.
      title: (--title) Take absolute value of time traces.
      indent_left: (--indent_left) A number in the [-0.11,0.88] range by which to shift the left boundary of the plot.
      add_width: (--add_width) A number in the [-0.86,0.13] range by which to increase the width the plot.
      saveas: (--saveas) Name of figure file.
    """
    return self._run(_cmd("gk-energy-balance"), name=name, species=species, path=path, relative_error=relative_error, multib=multib, field_dot_file=field_dot_file, apar_dot_file=apar_dot_file, fdot_file=fdot_file, source_file=source_file, bflux_xlower_file=bflux_xlower_file, bflux_ylower_file=bflux_ylower_file, bflux_zlower_file=bflux_zlower_file, bflux_xupper_file=bflux_xupper_file, bflux_yupper_file=bflux_yupper_file, bflux_zupper_file=bflux_zupper_file, f_file=f_file, field_file=field_file, apar_file=apar_file, dt_file=dt_file, logy=logy, absy=absy, xlabel=xlabel, ylabel=ylabel, title=title, indent_left=indent_left, add_width=add_width, saveas=saveas)

  def gk_fluxsurf(self,
      mapc2p: str | None = None,
      nodes: str | None = None,
      x_idx: int = 0,
      nphi: int = 128,
      nz_interp: int = 8,
      use: str | None = None,
      tag: str = 'fluxsurf',
      label: str | None = None):
    """Gyrokinetics: Extract a 2D theta-phi flux surface.

This command extracts data along a specific radial flux surface (constant x)
for 3D field-aligned data. It achieves this by performing a binormal
projection over a scan of toroidal angles (phi), creating a 2D grid of
phi vs z (where z maps along the poloidal/theta direction).

    Args:
      mapc2p: (--mapc2p, -m) Use a modal mapc2p file as the geometry source instead of the default nodes file.
      nodes: (--nodes, -n) Path to a nodal geometry file, overriding the default lookup.
      x_idx: (--x-idx, -x) The cell index in the radial (x) direction representing the flux surface. Default 0.
      nphi: (--nphi) Number of toroidal angle (phi) slices. Increased default to 128 for smoother diagonal field lines.
      nz_interp: (--nz-interp) Parallel (z) up-sampling factor used to smooth the projected 3D surfaces. Default 8.
      use: (--use, -u) Specify tag of datasets to process from the stack.
      tag: (--tag, -t) Tag for output datasets.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("gk-fluxsurf"), mapc2p=mapc2p, nodes=nodes, x_idx=x_idx, nphi=nphi, nz_interp=nz_interp, use=use, tag=tag, label=label)

  def gk_load_quantity(self,
      quantity: str | None = None,
      qlist: bool = False,
      name: str | None = None,
      species: str | None = None,
      frame: str | None = None,
      path: str = './',
      tag: str = 'default',
      label: str | None = None,
      extra: str | None = None):
    """Gyrokinetics: load a pre-named quantity from simulation output files.


For a list of accepted quantities use:
  pgkyl gk-load-quantity --qlist


Command line example:
  pgkyl gk-load-quantity den -s ion -n gk_sheath_2x2v_p1 -f 9 interp plot


Script example:
  from postgkyl.commands.gk_load_quantity import load_gk_quantity
  gdat = load_gk_quantity("n", "ion", "gk_sheath_2x2v_p1", frame=9)

    Args:
      quantity: (--quantity, -q) Quantity to plot.
      qlist: (--qlist) List accepted quantities.
      name: (--name, -n) Simulation name prefix (e.g. gk_sheath_2x2v_p1).
      species: (--species, -s) Species name (e.g. ion or elc).
      frame: (--frame, -f) Frame number, comma-separated list, or range 'start:stop[:step]'. Use ':' for all available frames.
      path: (--path, -p) Directory containing the simulation files.
      tag: (--tag, -t) Tag for the output dataset.
      label: (--label, -l) Label override for the output dataset.
      extra: (--extra, -e) Extra comma-separated key=value pairs of extra commands, e.g. dir=1,mass=0.1. A key may be given one value per species as a comma-separated array, e.g. mass=me,mi1,mi2 alongside --species elc,ion1,ion2. Purpose depends on -q.
    """
    return self._run(_cmd("gk-load-quantity"), quantity=quantity, qlist=qlist, name=name, species=species, frame=frame, path=path, tag=tag, label=label, extra=extra)

  def gk_nodes(self,
      name: str | None = None,
      path: str = './.',
      multib: str = '-10',
      nodes_file: str | None = None,
      psi_file: str | None = None,
      wall_file: str | None = None,
      contour: bool = False,
      clevels: str | None = None,
      cnlevels: int = 11,
      fixaspect: bool = False,
      xlim: str | None = None,
      ylim: str | None = None,
      xlabel: str = 'R (m)',
      ylabel: str = 'Z (m)',
      zlabel: str = '$\\psi$',
      title: str | None = None,
      indent_left: float = 0.0,
      add_width: float = 0.0,
      multib_unicolor: bool = False,
      saveas: str | None = None,
      no_show: bool = False):
    """
Gyrokinetics: Plot nodes of the grid, with an option to overlay
contours of the poloidal flux.


The default assumes these are in the current directory.
Alternatively, the full path to each file can be specified.


If simulation is multiblock, and you wish to specify files manually:
  1) Pass * for the block index.
  2) Use --multib/-m to specify desired blocks (or ommit to use all).

NOTE: this command cannot be combined with other postgkyl commands.

    Args:
      name: (--name, -n) Simulation name (also the file prefix, e.g. gk_sheath_1x2v_p1).
      path: (--path, -p) Path to simulation data.
      multib: (--multib, -m) Multiblock. Optional: pass block indices as comma-separated list or slice (start:stop:step). If no indices are given, all blocks are used.
      nodes_file: (--nodes_file) Grid nodes (.gkyl format).
      psi_file: (--psi_file) Poloidal flux (.gkyl format).
      wall_file: (--wall_file) Vacuum vessel wall (.csv format).
      contour: (--contour, -c) Plot contours of psi.
      clevels: (--clevels) Specify levels for contours: comma-separated level values or start:end:nlevels.
      cnlevels: (--cnlevels) Specify the number of levels for contours.
      fixaspect: (--fix_aspect, -a) Enforce the same scaling on both axes.
      xlim: (--xlim) Set limits for the x-coordinate (lower,upper)
      ylim: (--ylim) Set limits for the y-coordinate (lower,upper).
      xlabel: (--xlabel) Label for the x axis.
      ylabel: (--ylabel) Label for the y axis.
      zlabel: (--zlabel) Label for the color bar.
      title: (--title) Title for the figure.
      indent_left: (--indent_left) A number in the [-0.11,0.88] range by which to shift the left boundary of the plot.
      add_width: (--add_width) A number in the [-0.86,0.13] range by which to increase the width the plot.
      multib_unicolor: (--multib_unicolor) Use one color for all blocks.
      saveas: (--saveas) Name of figure file.
      no_show: (--no_show) Suppreses showing the figure.
    """
    return self._run(_cmd("gk-nodes"), name=name, path=path, multib=multib, nodes_file=nodes_file, psi_file=psi_file, wall_file=wall_file, contour=contour, clevels=clevels, cnlevels=cnlevels, fixaspect=fixaspect, xlim=xlim, ylim=ylim, xlabel=xlabel, ylabel=ylabel, zlabel=zlabel, title=title, indent_left=indent_left, add_width=add_width, multib_unicolor=multib_unicolor, saveas=saveas, no_show=no_show)

  def gk_particle_balance(self,
      name: str | None = None,
      species: str | None = None,
      path: str = './.',
      relative_error: bool = False,
      multib: str = '-10',
      fdot_file: tuple[str, ...] = None,
      source_file: tuple[str, ...] = None,
      bflux_xlower_file: tuple[str, ...] = None,
      bflux_ylower_file: tuple[str, ...] = None,
      bflux_zlower_file: tuple[str, ...] = None,
      bflux_xupper_file: tuple[str, ...] = None,
      bflux_yupper_file: tuple[str, ...] = None,
      bflux_zupper_file: tuple[str, ...] = None,
      f_file: tuple[str, ...] = None,
      dt_file: str | None = None,
      logy: bool = False,
      absy: bool = False,
      xlabel: str = 'Time (s)',
      ylabel: str | None = None,
      title: str | None = None,
      indent_left: float = 0.0,
      add_width: float = 0.0,
      saveas: str | None = None):
    """
Gyrokinetics: Plot the particle balance of a given species.
Requires the following files:
  ..._fdot_integrated_moms.gkyl
  ..._source_integrated_moms.gkyl
  ..._bflux_<direction><side>_integrated_HamiltonianMoments.gkyl
where ... means <simulation_name>-<species_name>.
The last two files above are only needed if the simulation had
sources or non-periodic boundaries. If the relative error is
requested, these are also needed:
  ..._integrated_moms.gkyl
  <simulation_name>-dt.gkyl


The default assumes these are in the current directory.
Alternatively, the full path to each file can be specified.


If simulation is multiblock, and you wish to specify files manually:
  1) Pass * for the block index.
  2) Use --multib/-m to specify desired blocks (or ommit to use all).

NOTE: this command cannot be combined with other postgkyl commands.

    Args:
      name: (--name, -n) Simulation name (also the file prefix, e.g. gk_sheath_1x2v_p1).
      species: (--species, -s) Species name.
      path: (--path, -p) Path to simulation data.
      relative_error: (--relative_error, -r) Plot the relative error only.
      multib: (--multib, -m) Multiblock. Optional: pass block indices as comma-separated list or slice (start:stop:step). If no indices are given, all blocks are used.
      fdot_file: (--fdot_file) Integrated moments of change in f over a time step.
      source_file: (--source_file) Integrated moments of the source(s).
      bflux_xlower_file: (--bflux_xlower_file) Integrated moments of boundary flux through lower x boundary.
      bflux_ylower_file: (--bflux_ylower_file) Integrated moments of boundary flux through lower y boundary.
      bflux_zlower_file: (--bflux_zlower_file) Integrated moments of boundary flux through lower z boundary.
      bflux_xupper_file: (--bflux_xupper_file) Integrated moments of boundary flux through upper x boundary.
      bflux_yupper_file: (--bflux_yupper_file) Integrated moments of boundary flux through upper y boundary.
      bflux_zupper_file: (--bflux_zupper_file) Integrated moments of boundary flux through upper z boundary.
      f_file: (--f_file) Integrated moments of f.
      dt_file: (--dt_file) Time step.
      logy: (--logy) Logarithmic scale for y axis.
      absy: (--absy) Take absolute value of time traces.
      xlabel: (--xlabel) Label for the x axis.
      ylabel: (--ylabel) Label for the y axis.
      title: (--title) Take absolute value of time traces.
      indent_left: (--indent_left) A number in the [-0.11,0.88] range by which to shift the left boundary of the plot.
      add_width: (--add_width) A number in the [-0.86,0.13] range by which to increase the width the plot.
      saveas: (--saveas) Name of figure file.
    """
    return self._run(_cmd("gk-particle-balance"), name=name, species=species, path=path, relative_error=relative_error, multib=multib, fdot_file=fdot_file, source_file=source_file, bflux_xlower_file=bflux_xlower_file, bflux_ylower_file=bflux_ylower_file, bflux_zlower_file=bflux_zlower_file, bflux_xupper_file=bflux_xupper_file, bflux_yupper_file=bflux_yupper_file, bflux_zupper_file=bflux_zupper_file, f_file=f_file, dt_file=dt_file, logy=logy, absy=absy, xlabel=xlabel, ylabel=ylabel, title=title, indent_left=indent_left, add_width=add_width, saveas=saveas)

  def gk_rz(self,
      mapc2p: str | None = None,
      nodes: str | None = None,
      z_axis: float = 0.0,
      use: str | None = None,
      tag: str = 'rz',
      label: str | None = None,
      phi_tor: float = 0.0,
      nz_interp: int = 8):
    """
Gyrokinetics: Interpolate DG dataset(s) and map them to the R-Z plane.
Assumes DG data (not yet interpolated) has been loaded onto the stack by a
preceding command.

The geometry is automatically found from the prefix of the first processed
dataset: the pointwise '<prefix>-geo_int_nodes.gkyl' is preferred (exact node
coordinates, robust at coarse z resolution), falling back to the modal
'<prefix>-geo_int_mapc2p.gkyl'. Use '-n path' to point at a specific nodes
file, '-m path' at a specific mapc2p file, or "-m ''" to force the default
mapc2p lookup.

For 3D (field-aligned) data the field is reconstructed on the poloidal plane at
toroidal angle --phi-tor (default 0) by interpolating along the binormal
direction, up-sampled in z (--nz-interp) for smooth surfaces.

    Args:
      mapc2p: (--mapc2p, -m) Use a modal mapc2p file as the geometry source instead of the default nodes file; pass '' to look up '<prefix>-geo_int_mapc2p.gkyl' from the first processed dataset's prefix.
      nodes: (--nodes, -n) Path to a nodal geometry file, overriding the default '<prefix>-geo_int_nodes.gkyl' lookup.
      z_axis: (--z-axis, -z) Vertical position of the magnetic axis (m), added to the geometry Z.mapc2p files store Z relative to the axis; pass Z_axis from the simulation input file to plot in machine coordinates. Default 0.
      use: (--use, -u) Specify tag of datasets to process from the stack.
      tag: (--tag, -t) Tag for output datasets.
      label: (--label, -l) Custom label for the result.
      phi_tor: (--phi-tor, -p) Toroidal angle (radians) of the poloidal plane to project 3D data onto. Default 0.
      nz_interp: (--nz-interp) Parallel (z) up-sampling factor used to smooth the projected 3D surfaces. Default 8.
    """
    return self._run(_cmd("gk-rz"), mapc2p=mapc2p, nodes=nodes, z_axis=z_axis, use=use, tag=tag, label=label, phi_tor=phi_tor, nz_interp=nz_interp)

  def grid(self,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None,
      read: bool | None = None):
    """Create a dataset out of a grid

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
      read: (--read, -r) Read from general interpolation file.
    """
    return self._run(_cmd("grid"), use=use, tag=tag, label=label, read=read)

  def growth(self,
      use: str | None = None,
      guess: str | None = None,
      minn: int | None = None,
      dataset: bool = False,
      instantaneous: bool = False,
      dir: int | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Attempts to compute growth rate (i.e. fit e^(2x)) from DynVector data.

the DynVector is typically an integrated quantity like electric or magnetic field
energy.

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      guess: (-g, --guess) Specify comma-separated initial guess.
      minn: (--minn) Set minimal number of points to fit.
      dataset: (-d, --dataset) Create a new dataset with fitted exponential.
      instantaneous: (-i, --instantaneous) Plot instantaneous growth rate vs time.
      dir: (--dir) Choose direction for multi-D data.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("growth"), use=use, guess=guess, minn=minn, dataset=dataset, instantaneous=instantaneous, dir=dir, tag=tag, label=label)

  def info(self,
      use: str | None = None,
      compact: bool = False,
      allsets: bool = False):
    """Print info of active datasets.

    Args:
      use: (-u, --use) Specify a 'tag' to apply to (default all tags).
      compact: (-c, --compact) Show in compact mode.
      allsets: (-a, --allsets) All data sets.
    """
    return self._run(_cmd("info"), use=use, compact=compact, allsets=allsets)

  def integrate(self,
      axis: str,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """"Integrate data over a specified axis or axes.

    Args:
      axis: (axis)
      use: (--use, -u) Specify the tag to integrate.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("integrate"), axis=axis, use=use, tag=tag, label=label)

  def interpolate(self,
      basis_type: Literal['ms', 'ns', 'mo', 'mt', 'gkhyb', 'gkhyb_vel', 'pkpmhyb'] | None = None,
      poly_order: int | None = None,
      interp: int | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None,
      read: bool | None = None):
    """Interpolate DG data onto a uniform mesh.

    Args:
      basis_type: (--basis_type, -b) Specify DG basis.
      poly_order: (--poly_order, -p) Specify polynomial order.
      interp: (--interp, -i) Interpolation onto a general mesh of specified amount.
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
      read: (--read, -r) Read from general interpolation file.
    """
    return self._run(_cmd("interpolate"), basis_type=basis_type, poly_order=poly_order, interp=interp, use=use, tag=tag, label=label, read=read)

  def laguerrecompose(self,
      distribution: str | None = None,
      tm: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Compose PKPM Laguerre coefficients together.

    Args:
      distribution: (--distribution, -f) Specify the PKPM distribution function dataset.
      tm: (--tm) Specify the PKPM vars dataset.
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("laguerrecompose"), distribution=distribution, tm=tm, tag=tag, label=label)

  def listoutputs(self,
      extensions: str = 'bp,gkyl',
      path: str = '.'):
    """List Gkeyll filename stems in the current directory.

    Args:
      extensions: (--extensions, -e) Output file extension(s)
      path: (--path, -p) Path to search for outputs
    """
    return self._run(_cmd("listoutputs"), extensions=extensions, path=path)

  def magsq(self,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Calculate the magnitude squared of an input array.

    Args:
      use: (--use, -u) Specify the tag to integrate.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("magsq"), use=use, tag=tag, label=label)

  def mask(self,
      use: str | None = None,
      filename: str | None = None,
      lower: float | None = None,
      upper: float | None = None):
    """Mask data with specified Gkeyll mask file.

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      filename: (--filename, -f) Specify the file with a mask.
      lower: (--lower, -l) Specify the lower theshold to be masked out.
      upper: (--upper, -u) Specify the upper theshold to be masked out.
    """
    return self._run(_cmd("mask"), use=use, filename=filename, lower=lower, upper=upper)

  def mhd(self,
      use: str | None = None,
      mu0: float = 1.0,
      gas_gamma: float = 1.6666666666666667,
      variable_name: Literal['density', 'xvel', 'yvel', 'zvel', 'vel', 'Bx', 'By', 'Bz', 'Bi', 'magpressure', 'pressure', 'temp', 'sound', 'mach'] | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Compute ideal MHD primitive and some derived variables from MHD conserved variables.


    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      mu0: (--mu0, -m) Permeability of free space.
      gas_gamma: (--gas_gamma, -g) Gas adiabatic constant.
      variable_name: (--variable_name, -v) Variable to extract
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("mhd"), use=use, mu0=mu0, gas_gamma=gas_gamma, variable_name=variable_name, tag=tag, label=label)

  def mom_agyro(self,
      measure: Literal['swidak', 'frobenius'] = 'frobenius',
      species: str | None = None,
      field: str | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Compute a measure of agyrotropy. Default measure is taken from
Swisdak 2015. Optionally computes agyrotropy as Frobenius norm of
agyrotropic pressure tensor.

    Args:
      measure: (--measure, -m) Specify how to calculate agyrotropy.
      species: (--species, -s) Tag for input pressure.
      field: (--field, -f) Tag for input EM field.
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("mom-agyro"), measure=measure, species=species, field=field, tag=tag, label=label)

  def pkpm(self,
      name: str | None = None,
      species: str | None = None,
      idx: str | None = None,
      poly_order: int | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Shortcut to load Gkeyll PKPM data, interpolate, and transform.

    Args:
      name: (--name, -n) Set the root name for files.
      species: (--species, -s) Set species name.
      idx: (--idx, -i) Set the file number.
      poly_order: (--poly_order, -p) Set the polynomial order.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("pkpm"), name=name, species=species, idx=idx, poly_order=poly_order, tag=tag, label=label)

  def plot(self,
      use: str | None = None,
      figure: str | None = None,
      squeeze: bool = False,
      subplots: bool = False,
      num_subplot_row: int | None = None,
      num_subplot_col: int | None = None,
      transpose: bool = False,
      contour: bool = False,
      surface: bool = False,
      alpha: float | None = None,
      clevels: str | None = None,
      cnlevels: int | None = None,
      cont_label: bool = False,
      quiver: bool = False,
      streamline: bool = False,
      sdensity: int = 1,
      arrowstyle: str | None = None,
      lineouts: Literal['0', '1'] | None = None,
      scatter: bool = False,
      markersize: float | None = None,
      linewidth: float | None = None,
      linestyle: Literal['solid', 'dashed', 'dotted', 'dashdot'] | None = None,
      style: str | None = None,
      diverging: bool = False,
      arg: str = '',
      fixaspect: bool = False,
      aspect: str | None = None,
      logx: bool = False,
      logy: bool = False,
      logz: bool = False,
      xshift: float = 0.0,
      yshift: float = 0.0,
      zshift: float = 0.0,
      xscale: float = 1.0,
      yscale: float = 1.0,
      zscale: float = 1.0,
      xmax: float | None = None,
      xmin: float | None = None,
      ymax: float | None = None,
      ymin: float | None = None,
      zmax: float | None = None,
      zmin: float | None = None,
      xlim: str | None = None,
      ylim: str | None = None,
      zlim: str | None = None,
      relax: bool = False,
      globalrange: bool = False,
      cutoffglobalrange: float | None = None,
      legend: str | None = None,
      no_legend: bool = False,
      forcelegend: bool = False,
      color: str | None = None,
      xlabel: str | None = None,
      ylabel: str | None = None,
      clabel: str | None = None,
      title: str | None = None,
      subplot_titles: str | None = None,
      subplot_xlabels: str | None = None,
      subplot_ylabels: str | None = None,
      save: bool = False,
      saveas: str | None = None,
      dpi: int = 200,
      edgecolors: str | None = None,
      showgrid: bool = True,
      hashtag: bool = False,
      show: bool = True,
      figsize: str | None = None,
      saveframes: str | None = None,
      jet: bool = False,
      cmap: str | None = None,
      cval: str | None = None,
      multiblock: bool = False):
    """Plot active datasets, optionally displaying the plot and/or saving it to PNG files.

Plot labels can use a sub-set of LaTeX math commands placed between dollar ($) signs.

    Args:
      use: (--use, -u) Specify the tag to plot.
      figure: (--figure, -f) Specify figure to plot in; either number or 'dataset'.
      squeeze: (--squeeze) Squeeze the components into one panel.
      subplots: (--subplots, -b) Make subplots from multiple datasets.
      num_subplot_row: (--nsubplotrow) Manually set the number of rows for subplots.
      num_subplot_col: (--nsubplotcol) Manually set the number of columns for subplots.
      transpose: (--transpose) Transpose axes.
      contour: (-c, --contour) Make contour plot.
      surface: (--surface, --surf) Make a 3D surface plot for 2D data (auto-enabled when overlaying multiple 2D datasets).
      alpha: (--alpha) Surface transparency (0-1); useful when overlaying surfaces.
      clevels: (--clevels) Specify levels for contours: comma-separated level values or start:end:nlevels.
      cnlevels: (--cnlevels) Specify the number of levels for contours.
      cont_label: (--contlabel) Add labels to contours
      quiver: (-q, --quiver) Make quiver plot.
      streamline: (-l, --streamline) Make streamline plot.
      sdensity: (--sdensity) Control density of the streamlines.
      arrowstyle: (--arrowstyle) Set the style for streamline arrows.
      lineouts: (--lineouts) Switch to lineouts mode.
      scatter: (-s, --scatter) Make scatter plot.
      markersize: (--markersize) Set marker size for scatter plots.
      linewidth: (--linewidth) Set the linewidth.
      linestyle: (--linestyle) Set the linestyle.
      style: (--style) Specify Matplotlib style file (default: Postgkyl).
      diverging: (-d, --diverging) Switch to diverging color map.
      arg: (--arg) Additional plotting arguments, e.g., '*--'.
      fixaspect: (--fix-aspect, -a) Enforce the same scaling on both axes.
      aspect: (--aspect) Specify the scaling ratio.
      logx: (--logx) Set x-axis to log scale.
      logy: (--logy) Set y-axis to log scale.
      logz: (--logz) Set values of 2D plot to log scale.
      xshift: (--xshift) Value to shift the x-axis.
      yshift: (--yshift) Value to shift the y-axis.
      zshift: (--zshift) Value to shift the z-axis.
      xscale: (--xscale) Value to scale the x-axis.
      yscale: (--yscale) Value to scale the y-axis.
      zscale: (--zscale) Value to scale the z-axis (default: 1.0).
      xmax: (--xmax) Set maximal x-value.
      xmin: (--xmin) Set minimal x-values.
      ymax: (--ymax) Set maximal y-value.
      ymin: (--ymin) Set minimal y-values.
      zmax: (--zmax) Set maximal z-value.
      zmin: (--zmin) Set minimal z-values.
      xlim: (--xlim) Set limits for the x-coordinate (lower,upper)
      ylim: (--ylim) Set limits for the y-coordinate (lower,upper).
      zlim: (--zlim) Set limits for the z-coordinate (lower,upper).
      relax: (--relax) Relax the stringent x axis limits for 1D plots.
      globalrange: (--globalrange, -r) Make uniform extends across datasets.
      cutoffglobalrange: (--cutoffglobalrange, -cogr) Set custom limit for uniform across datasets
      legend: (--legend) If specified, comma-separated legend labels (e.g., 'a,b,c').
      no_legend: (--no-legend) Hide legend.
      forcelegend: (--force-legend) Force legend even when plotting a single dataset.
      color: (--color) Set color when available.
      xlabel: (-x, --xlabel) Specify a x-axis label.
      ylabel: (-y, --ylabel) Specify a y-axis label.
      clabel: (--clabel) Specify a label for colorbar.
      title: (--title) Specify a title.
      subplot_titles: (--subplot-titles) Comma-separated titles for each subplot. e.g. --subplot-titles 'Title1,Title2,Title3'
      subplot_xlabels: (--subplot-xlabels) Comma-separated x-axis labels for each subplot. e.g. --subplot-xlabels 'X1,X2,X3'
      subplot_ylabels: (--subplot-ylabels) Comma-separated y-axis labels for each subplot. e.g. --subplot-ylabels 'Y1,Y2,Y3'
      save: (--save) Save figure as PNG file.
      saveas: (--saveas) Name of figure file.
      dpi: (--dpi) DPI (resolution) for output.
      edgecolors: (-e, --edgecolors) Set color for cell edges to show grid outline.
      showgrid: (--showgrid) Show grid-lines.
      hashtag: (--hashtag) Turns on the pgkyl hashtag!
      show: (--show) Turn showing of the plot ON and OFF.
      figsize: (--figsize) Comma-separated values for x and y size.
      saveframes: (--saveframes) Save individual frames as PNGS instead of an opening them
      jet: (--jet) Turn colormap to jet for comparison with literature.
      cmap: (--cmap, --colormap) Override default colormap with a valid matplotlib cmap.
      cval: (--cval) For 1D plots, comma-separated values mapping each curve onto the colormap (e.g. '1e-6,2e-6'). Requires --cmap; defaults to the dataset index if omitted.
      multiblock: (-m, --multiblock)
    """
    return self._run(_cmd("plot"), use=use, figure=figure, squeeze=squeeze, subplots=subplots, num_subplot_row=num_subplot_row, num_subplot_col=num_subplot_col, transpose=transpose, contour=contour, surface=surface, alpha=alpha, clevels=clevels, cnlevels=cnlevels, cont_label=cont_label, quiver=quiver, streamline=streamline, sdensity=sdensity, arrowstyle=arrowstyle, lineouts=lineouts, scatter=scatter, markersize=markersize, linewidth=linewidth, linestyle=linestyle, style=style, diverging=diverging, arg=arg, fixaspect=fixaspect, aspect=aspect, logx=logx, logy=logy, logz=logz, xshift=xshift, yshift=yshift, zshift=zshift, xscale=xscale, yscale=yscale, zscale=zscale, xmax=xmax, xmin=xmin, ymax=ymax, ymin=ymin, zmax=zmax, zmin=zmin, xlim=xlim, ylim=ylim, zlim=zlim, relax=relax, globalrange=globalrange, cutoffglobalrange=cutoffglobalrange, legend=legend, no_legend=no_legend, forcelegend=forcelegend, color=color, xlabel=xlabel, ylabel=ylabel, clabel=clabel, title=title, subplot_titles=subplot_titles, subplot_xlabels=subplot_xlabels, subplot_ylabels=subplot_ylabels, save=save, saveas=saveas, dpi=dpi, edgecolors=edgecolors, showgrid=showgrid, hashtag=hashtag, show=show, figsize=figsize, saveframes=saveframes, jet=jet, cmap=cmap, cval=cval, multiblock=multiblock)

  def pr(self,
      use: str | None = None,
      grid: bool = False):
    """Print the data

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      grid: (--grid, -g) Print grid instead of values.
    """
    return self._run(_cmd("pr"), use=use, grid=grid)

  def relchange(self,
      use: str | None = None,
      index: int = 0,
      comp: str | None = None,
      tag: str = 'rel_change',
      label: str = 'delta'):
    """Computes the relative change between two datasets

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      index: (--index, -i) Dataset index for computing change relative to.
      comp: (--comp, -c) Dataset component to be compared to if user only wants to compare to a single component.
      tag: (--tag, -t) Tag for the result.
      label: (--label, -l) Custom label for the result/
    """
    return self._run(_cmd("relchange"), use=use, index=index, comp=comp, tag=tag, label=label)

  def select(self,
      z0: str | None = None,
      z1: str | None = None,
      z2: str | None = None,
      z3: str | None = None,
      z4: str | None = None,
      z5: str | None = None,
      comp: str | None = None,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None,
      multiblock: bool = False,
      multiframe: bool = False):
    """Subselect data from the active dataset(s).

This command allows, for example, to choose a specific component of a multi-component
dataset, select a index or coordinate range. Index ranges can also be specified using
python slice notation (start:end:stride).

    Args:
      z0: (--z0) Indices for 0th coord (either int, float, or slice).
      z1: (--z1) Indices for 1st coord (either int, float, or slice).
      z2: (--z2) Indices for 2nd coord (either int, float, or slice).
      z3: (--z3) Indices for 3rd coord (either int, float, or slice).
      z4: (--z4) Indices for 4th coord (either int, float, or slice).
      z5: (--z5) Indices for 5th coord (either int, float, or slice).
      comp: (--comp, -c) Indices for components (either int, slice, or coma-separated).
      use: (--use, -u) Specify a 'tag' to apply to.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result
      multiblock: (--multiblock, -m) Necessary parameter for multiblock lineouts in z0 or z1 dims
      multiframe: (--multiframe, -f) Specify if performing select on multiple multiblock frames
    """
    return self._run(_cmd("select"), z0=z0, z1=z1, z2=z2, z3=z3, z4=z4, z5=z5, comp=comp, use=use, tag=tag, label=label, multiblock=multiblock, multiframe=multiframe)

  def style(self,
      file: str | None = None,
      set: tuple[str, ...] = None,
      print: bool = False):
    """Probe and control the Matplotlib plotting style.

  The list of rcParams is available
  here:
https://matplotlib.org/stable/api/matplotlib_configuration_api.html

    Args:
      file: (--file, -f) Sets Maplotlib rcParams style file.
      set: (--set, -s) Sets individual rcParam(s) as 'key:value'.
      print: (--print, -p) Prints the current rcParams.
    """
    return self._run(_cmd("style"), file=file, set=set, print=print)

  def tenmoment(self,
      use: str | None = None,
      variable_name: Literal['density', 'xvel', 'yvel', 'zvel', 'vel', 'pressureTensor', 'pxx', 'pxy', 'pxz', 'pyy', 'pyz', 'pzz', 'pressure', 'temp', 'ke', 'sound', 'mach'] | None = None,
      gas_gamma: float = 1.6666666666666667,
      tag: str | None = None,
      label: str | None = None):
    """Extract ten-moment primitive variables from ten-moment conserved variables.


    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      variable_name: (-v, --variable_name) Variable to work with.
      gas_gamma: (-g, --gas_gamma) Gas adiabatic constant.
      tag: (--tag, -t) Optional tag for the resulting array
      label: (--label, -l) Custom label for the result
    """
    return self._run(_cmd("tenmoment"), use=use, variable_name=variable_name, gas_gamma=gas_gamma, tag=tag, label=label)

  def trajectory(self,
      fixaspect: bool = False,
      show: bool = True,
      interval: int = 100,
      save: bool = False,
      velocity: bool = True,
      saveas: str | None = None,
      elevation: float | None = None,
      azimuth: float | None = None,
      numframes: int | None = None,
      xmin: float | None = None,
      xmax: float | None = None,
      ymin: float | None = None,
      ymax: float | None = None,
      zmin: float | None = None,
      zmax: float | None = None,
      use: str | None = None):
    """Animate a particle trajectory.

    Args:
      fixaspect: (--fix-aspect) Enforce the same scaling on both axes.
      show: (--show) Turn showing of the plot ON and OFF (default: ON).
      interval: (-i, --interval) Specify the animation interval.
      save: (--save) Save figure as PNG.
      velocity: (--velocity) Plot velocity vectors.
      saveas: (--saveas) Name to save the plot as.
      elevation: (-e, --elevation) Set elevation.
      azimuth: (-a, --azimuth) Set azimuth.
      numframes: (-n, --numframes) Set number of frames for the animation.
      xmin: (--xmin) Minimum value of the x-coordinate
      xmax: (--xmax) Maximum value of the x-coordinate
      ymin: (--ymin) Minimum value of the y-coordinate
      ymax: (--ymax) Maximum value of the y-coordinate
      zmin: (--zmin) Minimum value of the z-coordinate
      zmax: (--zmax) Maximum value of the z-coordinate
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
    """
    return self._run(_cmd("trajectory"), fixaspect=fixaspect, show=show, interval=interval, save=save, velocity=velocity, saveas=saveas, elevation=elevation, azimuth=azimuth, numframes=numframes, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, zmin=zmin, zmax=zmax, use=use)

  def transformframe(self,
      distribution: str | None = None,
      bulk: str | None = None,
      cdim: int | None = None,
      tag: str | None = None,
      label: str | None = None):
    """Compose PKPM Laguerre coefficients together.

    Args:
      distribution: (--distribution, -f) Specify the PKPM distribution function.
      bulk: (--bulk, -u) Specify the PKPM moments.
      cdim: (--cdim, -c) Specify the number of configuration space dimensions.
      tag: (--tag, -t) Optional tag for the resulting array.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("transformframe"), distribution=distribution, bulk=bulk, cdim=cdim, tag=tag, label=label)

  def val2coord(self,
      use: str | None = None,
      tag: str | None = None,
      label: str | None = None,
      x: str | None = None,
      y: str | None = None,
      periodic: bool = False):
    """Given a dataset (typically a DynVector) selects columns from it to create new datasets.

For example, you can choose say column 1 to be the X-axis of the new dataset and
column 2 to be the Y-axis. Multiple columns can be choosen using range specifiers and
as many datasets are then created.

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      tag: (--tag, -t) Tag for the result.
      label: (--label, -l) Custom label for the result.
      x: (-x) Select components that will became the grid of the new dataset.
      y: (-y) Select components that will became the values of the new dataset.
      periodic: (--periodic, -p) Set the last component to match the first one.
    """
    return self._run(_cmd("val2coord"), use=use, tag=tag, label=label, x=x, y=y, periodic=periodic)

  def velocity(self,
      density: str = 'density',
      momentum: str = 'momentum',
      tag: str = 'velocity',
      label: str = 'velocity'):
    """velocity

    Args:
      density: (--density, -d) Tag for density.
      momentum: (--momentum, -m) Tag for momentum.
      tag: (--tag, -t) Tag for the result.
      label: (--label, -l) Custom label for the result.
    """
    return self._run(_cmd("velocity"), density=density, momentum=momentum, tag=tag, label=label)

  def write(self,
      use: str | None = None,
      filename: str | None = None,
      mode: Literal['gkyl', 'bp', 'txt', 'npy'] = 'gkyl',
      single: bool = False):
    """Write active dataset to a file.

The output file format can be set with ``--format``, and is Gkeyll's .gkyl by default.
Files saved as .gkyl or .bp can be later loaded back into pgkyl to further manipulate
or plot.

    Args:
      use: (--use, -u) Specify a 'tag' to apply to (default all tags).
      filename: (-f, --filename) Output file name.
      mode: (-m, --mode) Output file mode. One of `gkyl` (binary, default), `bp` (ADIOS BP file), `txt` (ASCII text file), or `npy` (NumPy binary file).
      single: (-s, --single) Write all dataset into one file
    """
    return self._run(_cmd("write"), use=use, filename=filename, mode=mode, single=single)
