"""Build a ``pgkyl`` command line from Python, one command per call.

A :class:`PostgkylSession` is the CLI driven from Python: every generated
command is a method with the command's own options, and each call runs the
command on the session's working set exactly as the ``pgkyl`` pipeline would::

    s = PostgkylSession()
    s.load("f.gkyl").interpolate(num_interp=3)
    s.select(z0=0.5)
    s.print_cli()  # pgkyl f.gkyl interpolate --num_interp 3 select --z0 0.5

Each command returns the session, so calls chain or stand alone alike; what
the last command returned (a figure, a printed value) is ``s.result``.

Nothing here is per-command. Methods are derived from ``MODELS``; a call is
spelled by ``command_tokens`` and those tokens are parsed and executed by the
same Click commands as ``pgkyl``, so the printed command line is the one that
ran. A call is refused unless the whole line still parses back into exactly
the recorded commands. Datasets referred to by an option (e.g. ``average
--weight``) are named by their ``tag``, as on the command line.

Static tools (IDEs, type checkers) cannot see methods made at runtime, so
``session.pyi`` declares them. It is generated by :func:`render_stub`
(``python scripts/generate_session_stub.py``), never edited by hand, and a
test fails while it is out of date.
"""

from __future__ import annotations

import inspect
import shlex
from typing import Any

import click

from postgkyl.cli.app import MODELS, cli
from postgkyl.cli.compiler import CommandModel, command_tokens, value_hint

_MODELS = {model.name: model for model in MODELS}


def _parse(context: click.Context, args: list[str]):
  """Parse the command at the head of ``args`` as ``pgkyl``'s chain does.

  Returns the command and its context; the context's ``args`` are the tokens
  left for the commands that follow.
  """
  name, command, rest = cli.resolve_command(context, list(args))
  return command, command.make_context(name,
                                       rest,
                                       parent=context,
                                       allow_extra_args=True,
                                       allow_interspersed_args=False)


def _check_round_trip(steps: list[list[str]]) -> None:
  """Raise ``ValueError`` unless ``steps`` joined parse back into ``steps``.

  Each step parses alone, but within a line an omitted optional positional
  argument (``integrate``'s ``axis``) would take the next command's name.
  """
  context = click.Context(cli, info_name="pgkyl")
  remaining = [token for step in steps for token in step]
  for step in steps:
    following = remaining[len(step):]
    _, parsed = _parse(context, remaining)
    remaining = parsed.args
    if remaining != following:
      taken = following[:len(following) - len(remaining)]
      raise ValueError(
          f"on the command line {shlex.join(step)!r} would read "
          f"{shlex.join(taken)!r} as its own argument; give {step[0]!r} "
          "its positional arguments explicitly")


class _Source(str):
  """Text that ``inspect`` prints verbatim, as an annotation or default."""

  def __repr__(self) -> str:
    return str(self)


_LITERALS = (type(None), bool, int, float, str)


def _default(value):
  """``value`` if its repr is Python source, otherwise ``...``."""
  if isinstance(value, _LITERALS) or (isinstance(value, tuple) and all(
      isinstance(item, _LITERALS) for item in value)):
    return value
  return _Source("...")


def _signature(model: CommandModel) -> inspect.Signature:
  """The command's options as a Python signature, without pipeline inputs."""
  return inspect.Signature([
      inspect.Parameter(parameter.name,
                        parameter.kind,
                        annotation=_Source(value_hint(parameter)),
                        default=(inspect.Parameter.empty if parameter.required
                                 else _default(parameter.default)))
      for parameter in model.parameters if not parameter.injected
  ],
                           return_annotation=_Source("PostgkylSession"))


def _doc(model: CommandModel) -> str:
  """The canonical callable's docstring, or the command help without one."""
  return inspect.getdoc(model.canonical) or model.long_help


class PostgkylSession:
  """A ``pgkyl`` pipeline built from Python that records its command line."""

  def __init__(self, *, no_show: bool = False) -> None:
    """Start an empty session.

    Args:
      no_show: Run every command that can open a window with ``no_show``,
        without recording it, so a GUI or a test shows nothing while the
        command line still opens its windows.
    """
    self._no_show = no_show
    self._context = click.Context(cli, info_name="pgkyl")
    # The group's own callback creates the working set, as on the CLI.
    self._context.invoke(cli.callback)
    self._steps: list[list[str]] = []
    self._result: Any = None

  def __getattr__(self, name: str):
    model = _MODELS.get(name)
    if model is None:
      raise AttributeError(
          f"{type(self).__name__!r} has no command or attribute {name!r}")
    signature = _signature(model)

    def run(*args, **kwargs):
      bound = signature.bind(*args, **kwargs)
      return self._run(model, bound.arguments)

    run.__name__ = name
    run.__qualname__ = f"{type(self).__name__}.{name}"
    run.__signature__ = signature
    run.__doc__ = _doc(model)
    return run

  def __dir__(self):
    return sorted(set(super().__dir__()) | set(_MODELS))

  def __repr__(self) -> str:
    return f"{type(self).__name__}({self.command()!r})"

  @property
  def datasets(self) -> tuple:
    """The working set: the datasets the next command applies to."""
    return tuple(self._context.obj.datasets)

  @property
  def result(self) -> Any:
    """What the last command returned, e.g. ``plot``'s figure."""
    return self._result

  def command(self) -> str:
    """The ``pgkyl`` command line equivalent to the calls made so far."""
    return shlex.join(
        ["pgkyl", *(token for step in self._steps for token in step)])

  def print_cli(self) -> None:
    """Print :meth:`command`."""
    print(self.command())

  def _run(self, model: CommandModel, values: dict) -> PostgkylSession:
    """Execute one command from the tokens it is recorded as.

    Returns the session, so commands chain; the command's own return value
    is :attr:`result`.
    """
    args = self._spelling(model, command_tokens(model, values))
    _check_round_trip([*self._steps, args])
    executed = args
    if self._no_show and any(parameter.name == "no_show"
                             for parameter in model.parameters):
      executed = self._spelling(
          model, command_tokens(model, {
              **values, "no_show": True
          }))
    command, context = _parse(self._context, executed)
    assert not context.args, context.args  # command_tokens spells one command
    result = command.invoke(context)
    # Recorded only once it has run, so a failed call leaves no trace.
    self._steps.append(args)
    self._result = result
    return self

  def _spelling(self, model: CommandModel, tokens: list[str]) -> list[str]:
    """``[name, *tokens]``, or the bare file name the CLI loads, if any."""
    if model.name == "load" and tokens[:1] == ["--file_name"]:
      bare = tokens[1:]
      if not bare[0].startswith("-"):
        try:
          name, _, _ = cli.resolve_command(self._context, list(bare))
        except click.UsageError:
          name = None
        if name == "load":
          return bare
    return [model.name, *tokens]


_STUB_HEADER = """\
# Generated by scripts/generate_session_stub.py from the CLI command models.
# Do not edit: tests/test_cli_session.py fails while this is out of date.
from collections.abc import Mapping
import os
from typing import Any, Literal

"""


def _stub_docstring(text: str | None, indent: str) -> str:
  """``text`` as a docstring statement at ``indent`` (``...`` without one)."""
  if not text:
    return f"{indent}..."
  if '"""' in text or text.endswith("\\"):
    return f"{indent}{text!r}"
  lines = [line.rstrip() for line in text.splitlines()]
  body = "\n".join(f"{indent}{line}" if line else "" for line in lines)
  return f'{indent}r"""{body.lstrip()}\n{indent}"""'


def _own_doc(member) -> str | None:
  """``member``'s own docstring, never one inherited from ``object``."""
  return inspect.cleandoc(member.__doc__) if member.__doc__ else None


def _stub_def(name: str, signature: inspect.Signature, doc: str | None) -> str:
  return f"    def {name}{signature}:\n{_stub_docstring(doc, '        ')}\n"


def _with_self(signature: inspect.Signature) -> inspect.Signature:
  this = inspect.Parameter("self", inspect.Parameter.POSITIONAL_OR_KEYWORD)
  return signature.replace(parameters=[this, *signature.parameters.values()])


def render_stub() -> str:
  """``session.pyi``: the session's own members, then one method per command."""
  members = []
  for name, member in vars(PostgkylSession).items():
    if name.startswith("_") and name != "__init__":
      continue
    if isinstance(member, property):
      signature = inspect.signature(member.fget, eval_str=True)
      members.append("    @property\n" +
                     _stub_def(name, signature, _own_doc(member)))
    elif inspect.isfunction(member):
      signature = inspect.signature(member, eval_str=True)
      members.append(_stub_def(name, signature, _own_doc(member)))
  for name in sorted(_MODELS):
    model = _MODELS[name]
    members.append(_stub_def(name, _with_self(_signature(model)), _doc(model)))
  doc = _stub_docstring(_own_doc(PostgkylSession), "    ")
  return (_STUB_HEADER + "class PostgkylSession:\n" + doc + "\n\n" +
          "\n".join(members))


__all__ = ["PostgkylSession", "render_stub"]
